package edu.wpi.car;

import java.io.PrintStream;

public class Hub extends PhysObj {

   public final Stud studA, studB, studC;
   	
	private Tire tire;

	public Tire getTire () { return tire; }

	public void setTire (Tire tire) { this.tire = tire; }

	public Hub (String name, Location location, Car parent) {
		super(name, location, parent);
		studA = new Stud(name+" stud A", Location.plus(location, 0, 0, 1), this);
		studB = new Stud(name+" stud B", Location.plus(location, 0, 0, -1), this);
		studC = new Stud(name+" stud C", Location.plus(location, 0, 0, 2), this);
	}

	// package copy constructor
	Hub (Hub hub, Car parent) {
	   super(hub.name, hub.location, parent);
	   studA = new Stud(hub.studA, this);
	   studB  = new Stud(hub.studB, this);
	   studC = new Stud(hub.studC, this);
	   tire = hub.getTire() == hub.world.LFtire ? world.LFtire :
	      hub.getTire() == hub.world.RFtire ? world.RFtire :
	         hub.getTire() == hub.world.RRtire ? world.RRtire :
	            hub.getTire() == hub.world.LRtire ? world.LRtire :
	               null;
	   if ( tire == null && hub.tire != null ) throw new IllegalStateException("Copy problem!");
	}
	
	@Override
   public void setLocation (Location location) {
      throw new UnsupportedOperationException("Cannot move a hub!");
   }
	
	@Override
   public void print (PrintStream stream, String indent) {
		indent = "  " + indent;
		stream.append(this.name + "\n");
		stream.append(indent + ".studA = ");
		studA.print(stream, indent);
		stream.append(indent + ".studB = ");
		studB.print(stream, indent);
		stream.append(indent + ".studC = ");
		studC.print(stream, indent);
		if ( tire != null) {
			stream.append(indent + "getTire() = ");
			tire.print(stream, indent);
		}
	}

	// equals and hashCode generated by Eclipse

   @Override
   public boolean equals (Object obj) {
      if ( this == obj )
         return true;
      if ( !super.equals(obj) )
         return false;
      if ( getClass() != obj.getClass() )
         return false;
      Hub other = (Hub) obj;
      if ( studA == null ) {
         if ( other.studA != null )
            return false;
      } else if ( !studA.equals(other.studA) )
         return false;
      if ( studB == null ) {
         if ( other.studB != null )
            return false;
      } else if ( !studB.equals(other.studB) )
         return false;
      if ( studC == null ) {
         if ( other.studC != null )
            return false;
      } else if ( !studC.equals(other.studC) )
         return false;
      if ( tire == null ) {
         if ( other.tire != null )
            return false;
      } else if ( !tire.equals(other.tire) )
         return false;
      return true;
   }
   
   @Override
   public int hashCode () {
      final int prime = 31;
      int result = super.hashCode();
      result = prime * result + ((studA == null) ? 0 : studA.hashCode());
      result = prime * result + ((studB == null) ? 0 : studB.hashCode());
      result = prime * result + ((studC == null) ? 0 : studC.hashCode());
      result = prime * result + ((tire == null) ? 0 : tire.hashCode());
      return result;
   }

}
