package edu.wpi.car;

import java.io.PrintStream;

public class Stud extends PhysObj {

   private Nut nut;
   
   public Nut getNut () { return nut; }

   public void setNut (Nut nut) { this.nut = nut; }
   
	public Stud (String name, Location location, Hub parent) {
		super(name, location, parent);
		setNut(new Nut(name+" nut", world));
	}

	// package copy constructor 
	Stud (Stud stud, Hub parent) {
	   super(stud.name, stud.location, parent);
	   if ( stud.nut != null ) nut = new Nut(stud.nut, world);
	}

	@Override
   public void setLocation (Location location) {
      throw new UnsupportedOperationException("Cannot move a stud!");
   }
	
	@Override
   public void print (PrintStream stream, String indent) {
		indent = indent + "  ";
		stream.append(this.name + "\n");
		if ( nut != null ) {
			stream.append(indent + "getNut() = ");
			nut.print(stream, indent);
		}
	}

	// equals and hashCode generated by Eclipse

   @Override
   public boolean equals (Object obj) {
      if ( this == obj )
         return true;
      if ( !super.equals(obj) )
         return false;
      if ( getClass() != obj.getClass() )
         return false;
      Stud other = (Stud) obj;
      if ( nut == null ) {
         if ( other.nut != null )
            return false;
      } else if ( !nut.equals(other.nut) )
         return false;
      return true;
   }
	
   @Override
   public int hashCode () {
      final int prime = 31;
      int result = super.hashCode();
      result = prime * result + ((nut == null) ? 0 : nut.hashCode());
      return result;
   }

}